sudo: false

language: go

go:
  - 1.6
  - tip

install:
  - wget --no-check-certificate https://www.colm.net/files/ragel/ragel-6.9.tar.gz
  - tar zxvf ragel-6.9.tar.gz
  - cd ragel-6.9 && ./configure --prefix=$HOME/ragel && make && make install
  - go get golang.org/x/tools/cmd/stringer
  - go install golang.org/x/tools/cmd/stringer
  - go install ./...
  - go install github.com/alamatic/alamatic/diag
  - PATH=$HOME/ragel/bin:$PATH go generate github.com/alamatic/alamatic/tokenizer

script:
  - go test github.com/alamatic/alamatic/diag github.com/alamatic/alamatic/tokenizer github.com/alamatic/alamatic/ast github.com/alamatic/alamatic/ir

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
