sudo: false

language: go

go:
  - 1.4
  - tip

addons:
  apt:
    packages:
      - ragel

install:
  - go get golang.org/x/tools/cmd/stringer
  - go install golang.org/x/tools/cmd/stringer
  - go generate github.com/alamatic/alamatic/tokenizer

script:
  - go test ./...

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
