language: python
python:
  - "2.7"
install:
  - "pip install -U pip"
  - "pip install -e . --use-mirrors"
  # FIXME: It'd be better not to duplicate the dependencies in here,
  # since they're already in setup.py. :(
  - "pip install --use-mirrors plex"
script: nosetests
